---
- name: Gather IOS Facts
  hosts: 10.23.2.21
  connection: local
  tasks:
    - name: Gather IOS Facts
      ios_facts:
        provider:
          host: 10.23.2.21
          port: 22
          authorize: yes
          auth_pass: V>zB!uHF@CG+Y8+R
          username: SVRAnsible
          password: V>zB!uHF@CG+Y8+R

    - name: What is the IOS OS ver?
      debug:
        var: ansible_net_version

    - name: What is the device model?
      debug:
        var: ansible_net_model

    - name: What is the hostname?
      debug:
        var: ansible_net_hostname

    - name: What are the IP addresses?
      debug:
        var: ansible_net_all_ipv4_addresses
...